-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 23:01:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DW_ESTACOES_GREEN
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DW_ESTACOES_GREEN
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DW_ESTACOES_GREEN` DEFAULT CHARACTER SET utf8 ;
USE `DW_ESTACOES_GREEN` ;

-- -----------------------------------------------------
-- Table `DW_ESTACOES_GREEN`.`DIM_TEMPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_ESTACOES_GREEN`.`DIM_TEMPO` (
  `idTEMPO` INT NOT NULL AUTO_INCREMENT,
  `Ano` INT NULL,
  `Mes` INT NULL,
  `dia` INT NULL,
  `Hora` INT NULL,
  `Minuto` INT NULL,
  PRIMARY KEY (`idTEMPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_ESTACOES_GREEN`.`DIM_ESTACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_ESTACOES_GREEN`.`DIM_ESTACAO` (
  `idDIM_ESTACAO` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idDIM_ESTACAO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_ESTACOES_GREEN`.`DIM_VENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_ESTACOES_GREEN`.`DIM_VENTO` (
  `idDIM_VENTO` INT NOT NULL AUTO_INCREMENT,
  `WindDir` FLOAT NULL,
  PRIMARY KEY (`idDIM_VENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_ESTACOES_GREEN`.`FATO_GREEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_ESTACOES_GREEN`.`FATO_GREEN` (
  `AirTC` FLOAT NULL,
  `Batt_Volt` FLOAT NULL,
  `Crnt_A` FLOAT NULL,
  `Piranometro_dif` FLOAT NULL,
  `PTemp_C` FLOAT NULL,
  `Rain_mm` FLOAT NULL,
  `BattV` FLOAT NULL,
  `TEMPO_idTEMPO` INT NOT NULL,
  `DIM_ESTACAO_idDIM_ESTACAO` INT NOT NULL,
  `DIM_VENTO_idDIM_VENTO` INT NOT NULL,
  `RH` FLOAT NULL,
  `Solar_KJ` FLOAT NULL,
  `Solar_Wm2` FLOAT NULL,
  `Tot24` FLOAT NULL,
  `WS_ms` FLOAT NULL,
  PRIMARY KEY (`TEMPO_idTEMPO`, `DIM_ESTACAO_idDIM_ESTACAO`, `DIM_VENTO_idDIM_VENTO`),
  INDEX `fk_FATO_GREEN_TEMPO_idx` (`TEMPO_idTEMPO` ASC) VISIBLE,
  INDEX `fk_FATO_GREEN_DIM_ESTACAO1_idx` (`DIM_ESTACAO_idDIM_ESTACAO` ASC) VISIBLE,
  INDEX `fk_FATO_GREEN_DIM_VENTO1_idx` (`DIM_VENTO_idDIM_VENTO` ASC) VISIBLE,
  CONSTRAINT `fk_FATO_GREEN_TEMPO`
    FOREIGN KEY (`TEMPO_idTEMPO`)
    REFERENCES `DW_ESTACOES_GREEN`.`DIM_TEMPO` (`idTEMPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_GREEN_DIM_ESTACAO1`
    FOREIGN KEY (`DIM_ESTACAO_idDIM_ESTACAO`)
    REFERENCES `DW_ESTACOES_GREEN`.`DIM_ESTACAO` (`idDIM_ESTACAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_GREEN_DIM_VENTO1`
    FOREIGN KEY (`DIM_VENTO_idDIM_VENTO`)
    REFERENCES `DW_ESTACOES_GREEN`.`DIM_VENTO` (`idDIM_VENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
